using UnityEngine;
using UnityEditor;
using System.Collections.Generic;

namespace ComponentBinder
{
    /// <summary>
    /// 组件绑定器Inspector扩展器
    /// 使用EditorUtility来在Inspector中添加绑定功能，避免与其他工具的冲突
    /// </summary>
    [InitializeOnLoad]
    public static class ComponentBinderInspectorExtension
    {
        static ComponentBinderInspectorExtension()
        {
            // 注册Inspector绘制回调
            EditorApplication.update += OnEditorUpdate;
            Selection.selectionChanged += OnSelectionChanged;
        }

        private static Dictionary<MonoBehaviour, ComponentBinderEditor> binderInstances = new();

        private static void OnSelectionChanged()
        {
            // 清理不再需要的实例
            var keysToRemove = new List<MonoBehaviour>();
            foreach (var key in binderInstances.Keys)
            {
                if (key == null) keysToRemove.Add(key);
            }
            foreach (var key in keysToRemove)
            {
                binderInstances.Remove(key);
            }
        }
        
        private static void OnEditorUpdate()
        {
            // 检查是否启用了组件绑定器
            if (!EditorPrefs.GetBool("ComponentBinder_ShowInInspector", false))
                return;
                
            // 获取当前选中的对象
            var selectedObject = Selection.activeObject;
            if (selectedObject is MonoBehaviour targetScript)
            {
                // 强制重绘Inspector以显示我们的绑定功能
                EditorUtility.SetDirty(targetScript);
            }
        }
        
        /// <summary>
        /// 在Inspector中添加组件绑定器
        /// 这个方法会被EditorUtility调用
        /// </summary>
        public static void DrawComponentBinderInInspector(MonoBehaviour target)
        {
            // 检查是否启用了组件绑定器
            if (!EditorPrefs.GetBool("ComponentBinder_ShowInInspector", false))
                return;
                
            // 检查脚本是否包含AutoGenerated区域
            bool hasRegion = ComponentBinderEditor.HasAutoGeneratedRegion(target);
            bool isBinding = binderInstances.ContainsKey(target);

            if (!hasRegion && !isBinding)
            {
                // 添加一个按钮来开始绑定
                EditorGUILayout.Space();
                EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
                EditorGUILayout.BeginHorizontal();
                EditorGUILayout.LabelField("Component Binder:", EditorStyles.boldLabel);
                if (GUILayout.Button("Start Binding", GUILayout.Width(200)))
                {
                    binderInstances[target] = new ComponentBinderEditor(target);
                }
                EditorGUILayout.EndHorizontal();
                return;
            }
            
            // 绘制组件绑定器
            if (!binderInstances.TryGetValue(target, out var binder))
            {
                binder = new ComponentBinderEditor(target);
                binderInstances[target] = binder;
            }
            
            EditorGUILayout.Space();
            EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
            binder.DrawComponentBinderInspector();
        }
        
        private static void AddAutoGeneratedRegion(string scriptPath)
        {
            string[] lines = System.IO.File.ReadAllLines(scriptPath);
            var fieldLines = new List<string>(lines);
            
            // 查找类的开始位置
            int classStartIndex = -1;
            for (int i = 0; i < fieldLines.Count; i++)
            {
                if (fieldLines[i].Contains("class") && fieldLines[i].Contains(":"))
                {
                    classStartIndex = i;
                    break;
                }
            }
            
            if (classStartIndex != -1)
            {
                // 找到类的开始大括号
                int braceIndex = classStartIndex;
                while (braceIndex < fieldLines.Count && !fieldLines[braceIndex].Contains("{"))
                    braceIndex++;
                
                if (braceIndex < fieldLines.Count)
                {
                    // 在第一个大括号后插入AutoGenerated区域
                    fieldLines.Insert(braceIndex + 1, "");
                    fieldLines.Insert(braceIndex + 2, "    #region AutoGenerated");
                    fieldLines.Insert(braceIndex + 3, "    // 拖拽的游戏对象和组件将自动生成在这里");
                    fieldLines.Insert(braceIndex + 4, "    #endregion");
                    fieldLines.Insert(braceIndex + 5, "");
                    
                    System.IO.File.WriteAllLines(scriptPath, fieldLines);
                    AssetDatabase.Refresh();
                    
                    Debug.Log($"已为脚本添加AutoGenerated区域: {scriptPath}");
                }
            }
        }
    }
}
