using UnityEditor;
using UnityEngine;
using System.Linq;

namespace ComponentBinder
{
    /// <summary>
    /// 组件绑定器菜单项
    /// 在Unity上方菜单栏中添加菜单项来控制组件绑定器的状态
    /// </summary>
    public static class ComponentBinderMenu
    {
        private const string MENU_PATH = "Tools/Component Binder/Toggle Inspector Binding";
        private const string PREFS_KEY = "ComponentBinder_ShowInInspector";
        
        [MenuItem(MENU_PATH)]
        public static void ToggleComponentBinder()
        {
            bool currentState = EditorPrefs.GetBool(PREFS_KEY, false);
            bool newState = !currentState;
            EditorPrefs.SetBool(PREFS_KEY, newState);
            
            Debug.Log($"Component Binder {(newState ? "enabled" : "disabled")} in Inspector");
            
            // 刷新Inspector
            if (Selection.activeObject != null)
            {
                EditorUtility.SetDirty(Selection.activeObject);
            }
            EditorApplication.QueuePlayerLoopUpdate();
        }
        
        [MenuItem(MENU_PATH, true)]
        public static bool ValidateToggleComponentBinder()
        {
            bool isEnabled = EditorPrefs.GetBool(PREFS_KEY, false);
            Menu.SetChecked(MENU_PATH, isEnabled);
            return true;
        }
        
        [MenuItem("Tools/Component Binder/Settings")]
        public static void OpenSettings()
        {
            EditorWindow.GetWindow<ComponentBinderSettingsWindow>("Component Binder Settings");
        }
    }
    
    /// <summary>
    /// 组件绑定器设置窗口
    /// </summary>
    public class ComponentBinderSettingsWindow : EditorWindow
    {
        private const string PREFS_KEY = "ComponentBinder_ShowInInspector";
        
        private void OnGUI()
        {
            EditorGUILayout.LabelField("Component Binder Settings", EditorStyles.boldLabel);
            EditorGUILayout.Space();
            
            bool currentState = EditorPrefs.GetBool(PREFS_KEY, false);
            bool newState = EditorGUILayout.Toggle("Show in Inspector", currentState);
            
            if (newState != currentState)
            {
                EditorPrefs.SetBool(PREFS_KEY, newState);
                Debug.Log($"Component Binder {(newState ? "enabled" : "disabled")} in Inspector");
                
                // 刷新Inspector
                if (Selection.activeObject != null)
                {
                    EditorUtility.SetDirty(Selection.activeObject);
                }
                EditorApplication.QueuePlayerLoopUpdate();
            }
            
            EditorGUILayout.Space();
            EditorGUILayout.HelpBox("When enabled, Component Binder will appear at the bottom of Inspector for MonoBehaviour scripts that contain #region AutoGenerated.", MessageType.Info);
            
            EditorGUILayout.Space();
            if (GUILayout.Button("Add AutoGenerated Region to Selected Script"))
            {
                AddAutoGeneratedRegionToSelectedScript();
            }
        }
        
        private void AddAutoGeneratedRegionToSelectedScript()
        {
            if (Selection.activeObject is MonoScript script)
            {
                string scriptPath = AssetDatabase.GetAssetPath(script);
                if (System.IO.File.Exists(scriptPath))
                {
                    AddAutoGeneratedRegion(scriptPath);
                }
                else
                {
                    Debug.LogWarning("Cannot find script file path.");
                }
            }
            else
            {
                Debug.LogWarning("Please select a MonoScript in the Project window.");
            }
        }
        
        private void AddAutoGeneratedRegion(string scriptPath)
        {
            string[] lines = System.IO.File.ReadAllLines(scriptPath);
            var fieldLines = new System.Collections.Generic.List<string>(lines);
            
            // 检查是否已经存在AutoGenerated区域
            if (lines.Any(line => line.Contains("#region AutoGenerated")))
            {
                Debug.LogWarning("Script already contains an AutoGenerated region.");
                return;
            }
            
            // 查找类的开始位置
            int classStartIndex = -1;
            for (int i = 0; i < fieldLines.Count; i++)
            {
                if (fieldLines[i].Contains("class") && fieldLines[i].Contains(":"))
                {
                    classStartIndex = i;
                    break;
                }
            }
            
            if (classStartIndex != -1)
            {
                // 找到类的开始大括号
                int braceIndex = classStartIndex;
                while (braceIndex < fieldLines.Count && !fieldLines[braceIndex].Contains("{"))
                    braceIndex++;
                
                if (braceIndex < fieldLines.Count)
                {
                    // 在第一个大括号后插入AutoGenerated区域
                    fieldLines.Insert(braceIndex + 1, "");
                    fieldLines.Insert(braceIndex + 2, "    #region AutoGenerated");
                    fieldLines.Insert(braceIndex + 3, "    // 拖拽的游戏对象和组件将自动生成在这里");
                    fieldLines.Insert(braceIndex + 4, "    #endregion");
                    fieldLines.Insert(braceIndex + 5, "");
                    
                    System.IO.File.WriteAllLines(scriptPath, fieldLines);
                    AssetDatabase.Refresh();
                    
                    Debug.Log($"已为脚本添加AutoGenerated区域: {scriptPath}");
                }
            }
            else
            {
                Debug.LogWarning("Cannot find class declaration in the script.");
            }
        }
    }
}
