using UnityEngine;
using UnityEditor;

namespace ComponentBinder
{
    /// <summary>
    /// 组件绑定器Inspector绘制器
    /// 在Inspector中显示组件绑定功能
    /// </summary>
    [CustomEditor(typeof(MonoBehaviour), true)]
    [CanEditMultipleObjects]
    public class ComponentBinderInspectorDrawer : UnityEditor.Editor
    {
        private ComponentBinderEditor componentBinder;
        private const string PREFS_KEY = "ComponentBinder_ShowInInspector";
        
        public override void OnInspectorGUI()
        {
            // 检查是否启用了组件绑定器
            if (EditorPrefs.GetBool(PREFS_KEY, false))
            {
                bool hasRegion = ComponentBinderEditor.HasAutoGeneratedRegion((MonoBehaviour)target);
                
                if (!hasRegion && componentBinder == null)
                {
                    // 显示开始绑定按钮
                    EditorGUILayout.Space();
                    EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
                    EditorGUILayout.BeginHorizontal();
                    EditorGUILayout.LabelField("Component Binder:", EditorStyles.boldLabel);
                    if (GUILayout.Button("Start Binding", GUILayout.Width(200)))
                    {
                        componentBinder = new ComponentBinderEditor((MonoBehaviour)target);
                    }
                    EditorGUILayout.EndHorizontal();
                    EditorGUILayout.Space();
                    EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
                }
                else
                {
                    // 绘制组件绑定器
                    if (componentBinder == null)
                    {
                        componentBinder = new ComponentBinderEditor((MonoBehaviour)target);
                    }
                    
                    EditorGUILayout.Space();
                    EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
                    componentBinder.DrawComponentBinderInspector();
                    EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
                }
            }

            // 绘制默认Inspector
            DrawDefaultInspector();
        }
        
        private void AddAutoGeneratedRegion(string scriptPath)
        {
            string[] lines = System.IO.File.ReadAllLines(scriptPath);
            var fieldLines = new System.Collections.Generic.List<string>(lines);
            
            // 查找类的开始位置
            int classStartIndex = -1;
            for (int i = 0; i < fieldLines.Count; i++)
            {
                if (fieldLines[i].Contains("class") && fieldLines[i].Contains(":"))
                {
                    classStartIndex = i;
                    break;
                }
            }
            
            if (classStartIndex != -1)
            {
                // 找到类的开始大括号
                int braceIndex = classStartIndex;
                while (braceIndex < fieldLines.Count && !fieldLines[braceIndex].Contains("{"))
                    braceIndex++;
                
                if (braceIndex < fieldLines.Count)
                {
                    // 在第一个大括号后插入AutoGenerated区域
                    fieldLines.Insert(braceIndex + 1, "");
                    fieldLines.Insert(braceIndex + 2, "    #region AutoGenerated");
                    fieldLines.Insert(braceIndex + 3, "    // 拖拽的游戏对象和组件将自动生成在这里");
                    fieldLines.Insert(braceIndex + 4, "    #endregion");
                    fieldLines.Insert(braceIndex + 5, "");
                    
                    System.IO.File.WriteAllLines(scriptPath, fieldLines);
                    AssetDatabase.Refresh();
                    
                    Debug.Log($"已为脚本添加AutoGenerated区域: {scriptPath}");
                }
            }
        }
    }
}
