using UnityEngine;
using UnityEditor;
using ComponentBinder;
using System.Collections.Generic;
using System.Linq;

/// <summary>
/// 通用组件绑定器 - 可以自动为所有MonoBehaviour添加组件绑定功能
/// 使用方法：
/// 1. 在Unity工具栏上点击Component Binder按钮来启用/禁用功能
/// 2. 在需要绑定功能的脚本中添加 #region AutoGenerated 和 #endregion
/// 3. 在Inspector中就会自动显示组件绑定功能
/// </summary>
[InitializeOnLoad]
public class UniversalComponentBinder
{
    private static Dictionary<MonoBehaviour, ComponentBinderEditor> binderInstances = new();
    private const string PREFS_KEY = "ComponentBinder_ShowInInspector";
    
    static UniversalComponentBinder()
    {
        // 注册Inspector绘制回调
        EditorApplication.update += OnEditorUpdate;
        
        // 当选择对象改变时，清理旧的实例
        Selection.selectionChanged += OnSelectionChanged;
    }
    
    private static void OnEditorUpdate()
    {
        // 检查是否启用了组件绑定器
        if (!EditorPrefs.GetBool(PREFS_KEY, false))
            return;
            
        // 获取当前选中的对象
        var selectedObject = Selection.activeObject;
        if (selectedObject is MonoBehaviour targetScript)
        {
            // 检查脚本是否包含AutoGenerated区域
            if (ComponentBinderEditor.HasAutoGeneratedRegion(targetScript))
            {
                // 确保有对应的ComponentBinderEditor实例
                if (!binderInstances.ContainsKey(targetScript))
                {
                    binderInstances[targetScript] = new ComponentBinderEditor(targetScript);
                }
            }
        }
    }
    
    private static void OnSelectionChanged()
    {
        // 清理不再需要的实例
        var keysToRemove = binderInstances.Keys.Where(key => key == null || !binderInstances.ContainsKey(key)).ToList();
        foreach (var key in keysToRemove)
        {
            binderInstances.Remove(key);
        }
    }
    
            /// <summary>
        /// 在Inspector中添加组件绑定器区域
        /// 这个方法会被EditorUtility调用
        /// </summary>
        [DrawGizmo(GizmoType.Selected)]
        public static void DrawComponentBinderInInspector(MonoBehaviour target, GizmoType gizmoType)
        {
            // 这个方法只是为了满足DrawGizmo的要求，实际绘制在OnSceneGUI中
        }
    
    /// <summary>
    /// 在Inspector底部添加组件绑定器
    /// </summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void DrawComponentBinderInInspector(MonoBehaviour target)
    {
        // 检查是否启用了组件绑定器
        if (!EditorPrefs.GetBool(PREFS_KEY, false))
            return;
            
        // 检查脚本是否包含AutoGenerated区域
        bool hasRegion = ComponentBinderEditor.HasAutoGeneratedRegion(target);
        bool isBinding = binderInstances.ContainsKey(target);

        if (!hasRegion && !isBinding)
        {
            // 添加一个按钮来开始绑定
            EditorGUILayout.Space();
            EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField("Component Binder:", EditorStyles.boldLabel);
            if (GUILayout.Button("Start Binding", GUILayout.Width(200)))
            {
                binderInstances[target] = new ComponentBinderEditor(target);
            }
            EditorGUILayout.EndHorizontal();
            return;
        }
        
        // 绘制组件绑定器
        if (!binderInstances.TryGetValue(target, out var binder))
        {
            binder = new ComponentBinderEditor(target);
            binderInstances[target] = binder;
        }
        
        EditorGUILayout.Space();
        EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);
        binder.DrawComponentBinderInspector();
    }
    
    private static void AddAutoGeneratedRegion(string scriptPath)
    {
        string[] lines = System.IO.File.ReadAllLines(scriptPath);
        var fieldLines = new List<string>(lines);
        
        // 查找类的开始位置
        int classStartIndex = -1;
        for (int i = 0; i < fieldLines.Count; i++)
        {
            if (fieldLines[i].Contains("class") && fieldLines[i].Contains(":"))
            {
                classStartIndex = i;
                break;
            }
        }
        
        if (classStartIndex != -1)
        {
            // 找到类的开始大括号
            int braceIndex = classStartIndex;
            while (braceIndex < fieldLines.Count && !fieldLines[braceIndex].Contains("{"))
                braceIndex++;
            
            if (braceIndex < fieldLines.Count)
            {
                // 在第一个大括号后插入AutoGenerated区域
                fieldLines.Insert(braceIndex + 1, "");
                fieldLines.Insert(braceIndex + 2, "    #region AutoGenerated");
                fieldLines.Insert(braceIndex + 3, "    // 拖拽的游戏对象和组件将自动生成在这里");
                fieldLines.Insert(braceIndex + 4, "    #endregion");
                fieldLines.Insert(braceIndex + 5, "");
                
                System.IO.File.WriteAllLines(scriptPath, fieldLines);
                AssetDatabase.Refresh();
                
                Debug.Log($"已为脚本添加AutoGenerated区域: {scriptPath}");
            }
        }
    }
} 